### PR TITLE
An array index number

### PR DESCRIPTION
**Pull request by jumper423**

### CODE REVIEW

**Comment by elodszopos** [comment]
Let's go!

**Comment by iambumblehead** [comment]
The tests fail with this branch. What do you think of putting this behaviour behind a flag? for example,

```javascript
formurlencoded(obj, { isarrayindex : true });
```

**Comment by elodszopos** [comment]
I'd be more than happy to. Let's give @jumper423 a chance to respond.

**Comment by jumper423** [comment]
I can not think of a situation when you need a flag with a value of "false". So I think it is not necessary. 

I can correct tests. To do this?

**Comment by iambumblehead** [comment]
Current users of this script get arrays encoded as '[]'. I have not used index encoded array values myself and am not sure if it is a safe change to make... Do you think the tests should be changed or do you think a flag would be best? Would you explain which change is best for users of this script?

I will test it with an express service to see how express receives data encoded with these changes

**Comment by iambumblehead** [comment]
Express does parse these correctly...

**Comment by jumper423** [comment]
It's my pleasure. Later this loan. Justify your position and more specific tests will change.

**Comment by iambumblehead** [comment]
https://github.com/iambumblehead/form-urlencoded/pull/7/files#diff-b0c6eb3d1360da1d412741872efd9ef6R46

the "i" here would be undefined...

**Comment by iambumblehead** [comment]
@jumper423 what's going on :)

**Comment by jumper423** [comment]
If we have input

> {array:[1,2,3]}

We can convert it to 

> array[]=1&array[]=2&array[]=3

If the input 

```
{
   parent:[
      {array1:[1,2]},
      {array2:[3,4]}
   ]
}
```

It is necessary to convert to 

> parent[0][array1][]=1&parent[0][array1][]=2&parent[1][array2][]=3&parent[1][array2][]=4

At the same time get the following picture

> parent[][array1][]=1&parent[][array1][]=2&parent[][array2][]=3&parent[][array2][]=4

What comes out of this if decode execute.
```
{
   parent: [
      {
         array1: [1]
      },
     {
         array1: [2]
      },
      {
         array2: [3]
      },
      {
         array2: [4]
      },
   ]
}
```
When you do not set the digital code, he can not understand that it is one and the same element of the array and each time it creates a new one.

In addition, the key doesn't see the point. As they use this library. Should have meet the same problem when using multidimensional arrays.

You can also see the difference in the results for example on this resource.
[http://www.freeformatter.com/url-parser-query-string-splitter.html](http://www.freeformatter.com/url-parser-query-string-splitter.html)

Enter what happens in You and look at the answer

> http://site.com?parent%5B%5D%5Barray1%5D%5B%5D=1&parent%5B%5D%5Barray1%5D%5B%5D=2&parent%5B%5D%5Barray2%5D%5B%5D=3&parent%5B%5D%5Barray2%5D%5B%5D=4

And compare with my data

> http://site.com?parent%5B0%5D%5Barray1%5D%5B0%5D=1&parent%5B0%5D%5Barray1%5D%5B1%5D=2&parent%5B1%5D%5Barray2%5D%5B0%5D=3&parent%5B1%5D%5Barray2%5D%5B1%5D=4

I hope the example is clear.

Sorry to be so long responding.
If you have any questions, I will try to promptly answer them.

**Comment by iambumblehead** [comment]
I'm using express to look at the results... I understand what you are showing

**Comment by jumper423** [comment]
Можно так же сделать чтоб индексы не ставились когда все элементы массива имеют скалярный тип данных, тогда можно не нумеровать. 
Но в этом случае придётся пробегать по всему массиву и проверять. Не уверен что это оправданно для того чтоб сэкономить пару байт памяти при отправки http запроса.

**Comment by jumper423** [comment]
View to express, please, at least I checked in php.

**Comment by iambumblehead** [comment]
The output you gave above was parsed correctly by express. Do you want these changes be published to npm?

**Comment by jumper423** [comment]
Yes

**Comment by iambumblehead** [comment]
thank you, it is published as form-urlencoded@1.5.0

**Comment by elodszopos** [comment]
Thanks kind sir.

**Pull request merged**
